### PR TITLE
Added option to NOT invoke the generated Load method

### LINKED ISSUE #96: FeatureRequest: do NOT load on startup (but generate the Load method)
### Feature description

I would like to be able to NOT have the referenced assemblies load on startup, but at a certain point in the flow of my app (when some intializations have been made). This would require that the LoadTypesOnStartup method be generated as it is today (so I can call it whenever I want), but just not invoked on startup.
Seems to me like that should be easy to achieve (but I might be wrong here of course ;-)

### PR DESCRIPTION
**Pull request by wexman**
### Issues Resolved ### 

- fixes #96 

### API Changes ###
None
 
None

### Platforms Affected ### 
- All

### Behavioral Changes ###

None

### Testing Procedure ###

Did not test - cannot even build because of missing Visual Studio features!

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
1. Please add unit tests to test the configuration. 
2. Please update [LoadAssembliesOnStartup.Fody.xcf](https://github.com/Fody/LoadAssembliesOnStartup/blob/develop/src/LoadAssembliesOnStartup.Fody/LoadAssembliesOnStartup.Fody.xcf)
3. Not sure if I like the name. It's been a while since I've written this add-in, but does it already generate a Load method that can be called manually? If so, then I would opt for a more meaningful name such as "SkipLoadOnModuleInit" or something like that.

**Comment by wexman** [comment]
1. I'm having a difficulty adding test to the solution, because I cannot even build it - seems I'm missing a Visual Studio feature (Multilingual App Toolkit)...
2. Will do. What are these files actually? Don't know the extension .xcf, but it looks like xsd?
3. You're probably right about the name. And about the method ;-) It doesn't seem to be possible to call the generated method because the compiler doesn't know about it (which makes sense because it's generated into the assembly afterwards). Don't know how to fix that.

**Comment by GeertvanHorrik** [comment]
1. Multilingual App Toolkit => should be warnings?
2. This is indeed a xsd if I am not mistaken, maybe xcf stands for Xml Configuration Format or something Simon came up with.
3. If you change the name, then I can add the other stuff once approved

**Comment by tom-englert** [comment]
2. It's the xsd fragment that will be compiled into the final fodyweawers.xsd for each project

**Comment by GeertvanHorrik** [comment]
@tom-englert thanks for the clarification, much appreciated.

@wexman let me know when you made the changes to the config names, then I'll merge and work on the actual implementation.

**Pull request closed without merging**
